# Generated by Django 6.0.2 on 2026-02-10 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('backend', models.CharField(choices=[('grok', 'Grok'), ('chatgpt', 'ChatGPT'), ('other', 'Other')], max_length=50)),
                ('personality', models.TextField()),
                ('political_leaning', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('neutral', 'Neutral')], max_length=50)),
                ('beat', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('town', models.CharField(max_length=100)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.CharField(max_length=50)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityclub.reporter')),
            ],
        ),
    ]
